### ISSUE TITLE
SIFTPointMatchClient

### ISSUE THREAD

**Issue by martinschorb** [saalfeldlab/render#107]
Dear all,

I am trying to get these [pointmatch scripts](https://github.com/AllenInstitute/render-modules/tree/master/rendermodules/pointmatch) to run, but the spark client doesn't like the input.

I have checked the required parameters (`pairJson`,...) and they all exist and/or make sense.

What exactly is the `collection`? Is this generated before? I ran the script to generate the tile pairs, but its output did not contain any collection-related data.

I am calling:

```
software/spark-3.0.0-bin-hadoop3.2/bin/spark-submit --class org.janelia.render.client.spark.SIFTPointMatchClient $SPARK_SCRIPTDIR/target/render-ws-spark-client-2.1.1-SNAPSHOT-standalone.jar --baseDataUrl http://pc-emcf-16.embl.de:8080/render-ws/v1 --owner test --pairJson /g/emcf/schorb/tile_pairs_test1_mipmap_z_21900_to_22300_dist_0.json --SIFTfdSize 8 --SIFTminScale 0.38 --SIFTmaxScale 0.82 --SIFTsteps 3 --matchRod 0.9 --matchMaxEpsilon 20.0 --matchMinInlierRatio 0.0 --matchMinNumInliers 8 --matchMaxNumInliers 200 --maxFeatureCacheGb 1 --renderScale 0.3 --collection test123
```

and the output I get is just:

```
WARNING: An illegal reflective access operation has occurred
WARNING: Illegal reflective access by org.apache.spark.unsafe.Platform (file:/g/emcf/software/spark-3.0.0-bin-hadoop3.2/jars/spark-unsafe_2.12-3.0.0.jar) to constructor java.nio.DirectByteBuffer(long,int)
WARNING: Please consider reporting this to the maintainers of org.apache.spark.unsafe.Platform
WARNING: Use --illegal-access=warn to enable warnings of further illegal reflective access operations
WARNING: All illegal access operations will be denied in a future release
20/10/05 17:13:38 WARN NativeCodeLoader: Unable to load native-hadoop library for your platform... using builtin-java classes where applicable
log4j:WARN No appenders could be found for logger (org.janelia.render.client.ClientRunner).
log4j:WARN Please initialize the log4j system properly.
log4j:WARN See http://logging.apache.org/log4j/1.2/faq.html#noconfig for more info.

Usage: java -cp <render-module>-standalone.jar 
      org.janelia.render.client.spark.SIFTPointMatchClient [options]
  Options:
  * --pairJson
...
```

So something seems to be wrong with the parameters...

**Comment by trautmane** [comment]
The "collection" is the persisted container or grouping of a set of match data.  It does not need to exist prior to generation, but will (presumably) get populated by the generation process.  Can you post the full usage error message you are seeing and the full command line for the call to the SIFTPointMatchClient?  My best guess is that some required option (marked with asterisk in usage message) is missing from your call.

**Comment by martinschorb** [comment]
Hi Eric,

this is all the output I get:

```
$ /g/emcf/software/spark-3.0.0-bin-hadoop3.2/bin/spark-submit --class org.janelia.render.client.spark.SIFTPointMatchClient /g/emcf/software/render/render-ws-spark-client/target/render-ws-spark-client-2.1.1-SNAPSHOT-standalone.jar --baseDataUrl http://pc-emcf-16.embl.de:8080/render-ws/v1 --owner test --pairJson /g/emcf/schorb/tile_pairs_test1_mipmap_z_21900_to_22300_dist_0.json --SIFTfdSize 8 --SIFTminScale 0.38 --SIFTmaxScale 0.82 --SIFTsteps 3 --matchRod 0.9 --matchMaxEpsilon 20.0 --matchMinInlierRatio 0.0 --matchMinNumInliers 8 --matchMaxNumInliers 200 --maxFeatureCacheGb 1 --renderScale 0.3 --collection test123
WARNING: An illegal reflective access operation has occurred
WARNING: Illegal reflective access by org.apache.spark.unsafe.Platform (file:/g/emcf/software/spark-3.0.0-bin-hadoop3.2/jars/spark-unsafe_2.12-3.0.0.jar) to constructor java.nio.DirectByteBuffer(long,int)
WARNING: Please consider reporting this to the maintainers of org.apache.spark.unsafe.Platform
WARNING: Use --illegal-access=warn to enable warnings of further illegal reflective access operations
WARNING: All illegal access operations will be denied in a future release
20/10/05 17:13:38 WARN NativeCodeLoader: Unable to load native-hadoop library for your platform... using builtin-java classes where applicable
log4j:WARN No appenders could be found for logger (org.janelia.render.client.ClientRunner).
log4j:WARN Please initialize the log4j system properly.
log4j:WARN See http://logging.apache.org/log4j/1.2/faq.html#noconfig for more info.

Usage: java -cp <render-module>-standalone.jar 
      org.janelia.render.client.spark.SIFTPointMatchClient [options]
  Options:
  * --pairJson
      JSON file where tile pairs are stored (.json, .gz, or .zip)
    --SIFTfdSize
      SIFT feature descriptor size: how many samples per row and column
      Default: 8
    --SIFTmaxScale
      SIFT maximum scale: minSize * minScale < size < maxSize * maxScale
      Default: 0.85
    --SIFTminScale
      SIFT minimum scale: minSize * minScale < size < maxSize * maxScale
      Default: 0.5
    --SIFTsteps
      SIFT steps per scale octave
      Default: 3
  * --baseDataUrl
      Base web service URL for data (e.g. http://host[:port]/render-ws/v1)
    --clipHeight
      Number of full scale pixels to include in rendered clips of TOP/BOTTOM 
      oriented montage tiles
    --clipWidth
      Number of full scale pixels to include in rendered clips of LEFT/RIGHT 
      oriented montage tiles
  * --collection
      Match collection name
    --expectedParallelism
      Fail immediately if Spark Context parallelism does not match this value
    --fillWithNoise
      Fill each canvas image with noise before rendering to improve point 
      match derivation
      Default: true
    --help
      Display this note
    --matchFilter
      Identifies if and how matches should be filtered
      Default: SINGLE_SET
      Possible Values: [NONE, SINGLE_SET, CONSENSUS_SETS, AGGREGATED_CONSENSUS_SETS]
    --matchInterpolatedModelLambda
      Lambda for interpolated match filtering (omit for standard filtering)
    --matchIterations
      Match filter iterations
      Default: 1000
    --matchMaxEpsilon
      Minimal allowed transfer error for match filtering
      Default: 20.0
    --matchMaxNumInliers
      Maximum number of inliers for match filtering
    --matchMaxTrust
      Reject match candidates with a cost larger than maxTrust * median cost
      Default: 3.0
    --matchMinInlierRatio
      Minimal ratio of inliers to candidates for match filtering
      Default: 0.0
    --matchMinNumInliers
      Minimal absolute number of inliers for match filtering
      Default: 4
    --matchModelType
      Type of model for match filtering
      Default: AFFINE
      Possible Values: [TRANSLATION, RIGID, SIMILARITY, AFFINE]
    --matchRegularizerModelType
      Type of regularizer model for interpolated match filtering (omit for 
      standard filtering)
      Possible Values: [TRANSLATION, RIGID, SIMILARITY, AFFINE]
    --matchRod
      Ratio of distances for matches
      Default: 0.92
    --maxFeatureCacheGb
      Maximum number of gigabytes of features to cache
      Default: 2
  * --owner
      Match collection owner
    --renderFilterListName
      Apply this filter list to all rendering (overrides renderWithFilter 
      option) 
    --renderFullScaleHeight
      Full scale height for all rendered tiles
    --renderFullScaleWidth
      Full scale width for all rendered tiles
    --renderScale
      Render tiles at this scale
      Default: 1.0
    --renderWithFilter
      Render tiles using default ad-hoc filter for intensity correction
      Default: true
    --renderWithoutMask
      Render tiles without a mask
      Default: true
    --requireStoredFeatures
      indicates that an exception should be thrown when stored features cannot 
      be found (if omitted, missing features are extracted from dynamically 
      rendered canvases)
      Default: false
    --rootFeatureDirectory
      Root directory for saved feature lists (omit if features should be 
      extracted from dynamically rendered canvases)
```

**Comment by martinschorb** [comment]
looks exactly the same whether with or without the `collection` argument.

**Comment by martinschorb** [comment]
The Tile Pair File looks reasonable to me:

```
$ cat /g/emcf/schorb/tile_pairs_test1_mipmap_z_21900_to_22300_dist_0.json
{
  "renderParametersUrlTemplate" : "{baseDataUrl}/owner/test/project/RENDERmodule_TEST/stack/test1_mipmap/tile/{id}/render-parameters",
  "neighborPairs" : [
    {
      "p" : {
        "groupId" : "442",
        "id" : "0000.0012.00442",
        "relativePosition" : "LEFT"
      },
      "q" : {
        "groupId" : "442",
        "id" : "0000.0013.00442",
        "relativePosition" : "RIGHT"
      }
    },
    {
      "p" : {
        "groupId" : "442",
        "id" : "0000.0013.00442",
        "relativePosition" : "TOP"
      },
      "q" : {
        "groupId" : "442",
        "id" : "0000.0021.00442",
        "relativePosition" : "BOTTOM"
      }
    },
    {
      "p" : {
        "groupId" : "442",
        "id" : "0000.0013.00442",
        "relativePosition" : "LEFT"
      },
      "q" : {
        "groupId" : "442",
        "id" : "0000.0014.00442",
        "relativePosition" : "RIGHT"
      }
    },
    {
      "p" : {
        "groupId" : "442",
        "id" : "0000.0014.00442",
        "relativePosition" : "TOP"
      },
      "q" : {
        "groupId" : "442",
        "id" : "0000.0022.00442",
        "relativePosition" : "BOTTOM"
      }
    },
    {
      "p" : {
        "groupId" : "442",
        "id" : "0000.0021.00442",
        "relativePosition" : "TOP"
      },
      "q" : {
        "groupId" : "442",
        "id" : "0000.0029.00442",
        "relativePosition" : "BOTTOM"
      }
    },
    {
      "p" : {
        "groupId" : "442",
        "id" : "0000.0021.00442",
        "relativePosition" : "LEFT"
      },


    ...


      "p" : {
        "groupId" : "450",
        "id" : "0000.0037.00450",
        "relativePosition" : "LEFT"
      },
      "q" : {
        "groupId" : "450",
        "id" : "0000.0038.00450",
        "relativePosition" : "RIGHT"
      }
    },
    {
      "p" : {
        "groupId" : "450",
        "id" : "0000.0038.00450",
        "relativePosition" : "TOP"
      },
      "q" : {
        "groupId" : "450",
        "id" : "0000.0046.00450",
        "relativePosition" : "BOTTOM"
      }
    }
  ]
}

**Comment by trautmane** [comment]
Hi Martin,

Yeah - everything looks ok to me at first glance.  I'll take a closer look later today to see if I can determine what might be wrong.  One possibility is that we at Janelia (and likely the Allen too) are using older Spark versions (2.1.0 at Janelia).  I'll post here if/when I learn more ...

--Eric

**Comment by trautmane** [comment]
Hi Martin,

I tried poking at this a little and haven't had any luck.  The usage message you got does not contain any specific error (which you should get) before listing the usage details.   Your message looks like "--help" is getting inserted somewhere in the args, but I don't see that.  Are you running this through the Allen Institute's python script or directly from the command line?  If it's the former, can you try running from the command line and truncating everything after "--owner test"? 

```
software/spark-3.0.0-bin-hadoop3.2/bin/spark-submit \
  --class org.janelia.render.client.spark.SIFTPointMatchClient \
  $SPARK_SCRIPTDIR/target/render-ws-spark-client-2.1.1-SNAPSHOT-standalone.jar \
  --baseDataUrl http://pc-emcf-16.embl.de:8080/render-ws/v1 \
  --owner test
```

My hope is that you'll see an error message like:

```
ERROR: failed to parse command line arguments
The following options are required: [--pairJson], [--collection]
```

If that works (by failing properly), try running the full command from the command line next.

Let me know what you learn.  
I think you might run into other problems related to the newer Spark version if/when you get past this first issue - but I'll try to keep things positive for now :).

--Eric

**Comment by martinschorb** [comment]
Hi Eric,

I tried a few more things:

- Java 8 vs. 11: same result
- Truncated command as suggested: same result
- When I run the command without an active Spark session or point it to a nonsense server `spark-submit --master spark://junk.com ...`, it also fails the exact same way. This means something is wrong with the connection to spark...

**Comment by martinschorb** [comment]
- tried spark 2.4.7: same result

Tried the spark example class (without a valid spark instance) and get:
```
$ spark-3.0.0-bin-hadoop3.2/bin/spark-submit   --class org.apache.spark.examples.SparkPi   --master spark://junk.embl.de:7070 spark-3.0.0-bin-hadoop3.2/examples/jars/spark-examples_2.12-3.0.0.jar 100
WARNING: An illegal reflective access operation has occurred
WARNING: Illegal reflective access by org.apache.spark.unsafe.Platform (file:/g/emcf/software/spark-3.0.0-bin-hadoop3.2/jars/spark-unsafe_2.12-3.0.0.jar) to constructor java.nio.DirectByteBuffer(long,int)
WARNING: Please consider reporting this to the maintainers of org.apache.spark.unsafe.Platform
WARNING: Use --illegal-access=warn to enable warnings of further illegal reflective access operations
WARNING: All illegal access operations will be denied in a future release
20/10/06 08:59:59 WARN NativeCodeLoader: Unable to load native-hadoop library for your platform... using builtin-java classes where applicable
Using Spark's default log4j profile: org/apache/spark/log4j-defaults.properties
20/10/06 08:59:59 INFO SparkContext: Running Spark version 3.0.0
20/10/06 08:59:59 INFO ResourceUtils: ==============================================================
20/10/06 08:59:59 INFO ResourceUtils: Resources for spark.driver:

20/10/06 08:59:59 INFO ResourceUtils: ==============================================================
20/10/06 08:59:59 INFO SparkContext: Submitted application: Spark Pi
20/10/06 08:59:59 INFO SecurityManager: Changing view acls to: schorb
20/10/06 08:59:59 INFO SecurityManager: Changing modify acls to: schorb
20/10/06 08:59:59 INFO SecurityManager: Changing view acls groups to: 
20/10/06 08:59:59 INFO SecurityManager: Changing modify acls groups to: 
20/10/06 08:59:59 INFO SecurityManager: SecurityManager: authentication disabled; ui acls disabled; users  with view permissions: Set(schorb); groups with view permissions: Set(); users  with modify permissions: Set(schorb); groups with modify permissions: Set()
20/10/06 09:00:00 INFO Utils: Successfully started service 'sparkDriver' on port 4193.
20/10/06 09:00:00 INFO SparkEnv: Registering MapOutputTracker
20/10/06 09:00:00 INFO SparkEnv: Registering BlockManagerMaster
20/10/06 09:00:00 INFO BlockManagerMasterEndpoint: Using org.apache.spark.storage.DefaultTopologyMapper for getting topology information
20/10/06 09:00:00 INFO BlockManagerMasterEndpoint: BlockManagerMasterEndpoint up
20/10/06 09:00:00 INFO SparkEnv: Registering BlockManagerMasterHeartbeat
20/10/06 09:00:00 INFO DiskBlockManager: Created local directory at /tmp/blockmgr-aa376d26-ef42-4321-9fbe-345e15492250
20/10/06 09:00:00 INFO MemoryStore: MemoryStore started with capacity 434.4 MiB
20/10/06 09:00:00 INFO SparkEnv: Registering OutputCommitCoordinator
20/10/06 09:00:00 INFO Utils: Successfully started service 'SparkUI' on port 4040.
20/10/06 09:00:00 INFO SparkUI: Bound SparkUI to 0.0.0.0, and started at http://login.cluster.embl.de:4040
20/10/06 09:00:00 INFO SparkContext: Added JAR file:/g/emcf/software/spark-3.0.0-bin-hadoop3.2/examples/jars/spark-examples_2.12-3.0.0.jar at spark://login.cluster.embl.de:4193/jars/spark-examples_2.12-3.0.0.jar with timestamp 1601967600752
20/10/06 09:00:01 INFO StandaloneAppClient$ClientEndpoint: Connecting to master spark://junk.embl.de:7070...
20/10/06 09:00:01 WARN StandaloneAppClient$ClientEndpoint: Failed to connect to master junk.embl.de:7070
org.apache.spark.SparkException: Exception thrown in awaitResult: 
	at org.apache.spark.util.ThreadUtils$.awaitResult(ThreadUtils.scala:302)
	at org.apache.spark.rpc.RpcTimeout.awaitResult(RpcTimeout.scala:75)
...
```

with a very stripped down command to just try to start spark:

```
$ /g/emcf/software/spark-3.0.0-bin-hadoop3.2/bin/spark-submit --class org.janelia.render.client.spark.SIFTPointMatchClient --master spark://junk.embl.de:7070 /g/emcf/software/render/render-ws-spark-client/target/render-ws-spark-client-2.1.1-SNAPSHOT-standalone.jar
WARNING: An illegal reflective access operation has occurred
WARNING: Illegal reflective access by org.apache.spark.unsafe.Platform (file:/g/emcf/software/spark-3.0.0-bin-hadoop3.2/jars/spark-unsafe_2.12-3.0.0.jar) to constructor java.nio.DirectByteBuffer(long,int)
WARNING: Please consider reporting this to the maintainers of org.apache.spark.unsafe.Platform
WARNING: Use --illegal-access=warn to enable warnings of further illegal reflective access operations
WARNING: All illegal access operations will be denied in a future release
20/10/06 09:04:00 WARN NativeCodeLoader: Unable to load native-hadoop library for your platform... using builtin-java classes where applicable
log4j:WARN No appenders could be found for logger (org.janelia.render.client.ClientRunner).
log4j:WARN Please initialize the log4j system properly.
log4j:WARN See http://logging.apache.org/log4j/1.2/faq.html#noconfig for more info.

Usage: java -cp <render-module>-standalone.jar 
      org.janelia.render.client.spark.SIFTPointMatchClient [options]
  Options:

...
```
So the first difference is `log4j` and then it does not seem to start the spark submission at all.

**Comment by trautmane** [comment]
This looks like a problem with the newer Spark version.  This morning I used https://hub.docker.com/r/bitnami/spark/ to test running with Spark 3.0.1 and I got the same error as you.  When I reverted to Spark 2.4.3 (the earliest version available from bitnami), I got the correct error message.  I'll spend some time investigating what has changed with Spark to see if I can determine what is really going wrong.  I'll also check to see how difficult it is to install (much) older Spark.  As I mentioned earlier, we are using 2.1.0 at Janelia.

**Comment by trautmane** [comment]
This "worked" for me:

```
$ curl --output spark-2.4.7-bin-hadoop2.7.tgz https://archive.apache.org/dist/spark/spark-2.4.7/spark-2.4.7-bin-hadoop2.7.tgz
 
$ tar xzf spark-2.4.7-bin-hadoop2.7.tgz

$ java -version
java version "1.8.0_241"
Java(TM) SE Runtime Environment (build 1.8.0_241-b07)
Java HotSpot(TM) 64-Bit Server VM (build 25.241-b07, mixed mode)

$ spark-2.4.7-bin-hadoop2.7/bin/spark-submit --class org.janelia.render.client.spark.SIFTPointMatchClient /Users/trautmane/projects/git/render/render-ws-spark-client/target/render-ws-spark-client-2.3.1-SNAPSHOT-standalone.jar --baseDataUrl http://pc-emcf-16.embl.de:8080/render-ws/v1 --owner test --pairJson /g/emcf/schorb/tile_pairs_test1_mipmap_z_21900_to_22300_dist_0.json --SIFTfdSize 8 --SIFTminScale 0.38 --SIFTmaxScale 0.82 --SIFTsteps 3 --matchRod 0.9 --matchMaxEpsilon 20.0 --matchMinInlierRatio 0.0 --matchMinNumInliers 8 --matchMaxNumInliers 200 --maxFeatureCacheGb 1 --renderScale 0.3 --collection test123
...
20/10/06 11:35:53 INFO SparkContext: Running Spark version 2.4.7
20/10/06 11:35:53 INFO SparkContext: Submitted application: SIFTPointMatchClient
...
20/10/06 11:35:55 INFO SIFTPointMatchClient: run: appId is local-1601998554456, executors data is [ {
  "id" : "driver",
  ...
  "blacklistedInStages" : [ ]
} ]
20/10/06 11:35:55 INFO SIFTPointMatchClient: generateMatchesForPairFile: pairJsonFileName is /g/emcf/schorb/tile_pairs_test1_mipmap_z_21900_to_22300_dist_0.json
20/10/06 11:35:55 INFO RenderableCanvasIdPairs: load: entry, path=/g/emcf/schorb/tile_pairs_test1_mipmap_z_21900_to_22300_dist_0.json
20/10/06 11:35:55 ERROR ClientRunner: run: caught exception
java.io.FileNotFoundException: /g/emcf/schorb/tile_pairs_test1_mipmap_z_21900_to_22300_dist_0.json (No such file or directory)
	at java.io.FileInputStream.open0(Native Method)
	...
20/10/06 11:35:55 INFO ClientRunner: run: exit, processing failed after 0 hours, 0 minutes, 1 seconds
20/10/06 11:35:55 INFO SparkContext: Invoking stop() from shutdown hook
```

If you try this and get different results, the only other thing I can think of is that you aren't running with the java version you think you are.

**Comment by trautmane** [comment]
Hi Martin,
I found and fixed the source of this problem.  The key was first to:
`cp spark-3.0.1-bin-hadoop2.7/conf/log4j.properties.template spark-3.0.1-bin-hadoop2.7/conf/log4j.properties`
which got log4j working and revealed a jackson lib runtime error that was previously hidden from us.
Spark 3.0.1 includes jackson 2.11.0 whereas render was built with jackson 2.6.7.
I was able to fix the immediate problem with https://github.com/saalfeldlab/render/commit/30c8620e3d01650f9dde74f0e7078f932ec04198 which works in both old and new jackson versions.  I'm going to look at upgrading jackson and spark next, but that will take more time because I need to do more involved testing.  I'm interested to see how far you are able to get just with this one change.
--Eric

**Comment by martinschorb** [comment]
Fun fact:

I now see the help output during the maven build for pretty much all classes. Is this intentional...?

```
...

[INFO] Running org.janelia.render.client.spark.BoxRemovalClientTest

Usage: java -cp <render-module>-standalone.jar 
      org.janelia.render.client.spark.BoxRemovalClient [options]
  Options:
  * --baseDataUrl
      Base web service URL for data (e.g. http://host[:port]/render-ws/v1)
    --help
      Display this note
    --maxLevel
      Maximum mipmap level to remove (values > 8 will also delete small 
      overview images)
      Default: 9
    --maxZ
      Maximum Z value for layers to be processed
    --minLevel
      Minimum mipmap level to remove
      Default: 0
    --minZ
      Minimum Z value for layers to be processed
  * --owner
      Stack owner
  * --project
      Stack project
  * --stack
      Stack name
  * --stackDirectory
      Stack directory containing boxes to remove (e.g. 
      /tier2/flyTEM/nobackup/rendered_boxes/FAFB00/v7_align_tps/8192x8192) 

[INFO] Tests run: 1, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 0.004 s - in org.janelia.render.client.spark.BoxRemovalClientTest
[INFO] Running org.janelia.render.client.spark.HierarchicalAlignmentClientTest
[INFO] Tests run: 1, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 0 s - in org.janelia.render.client.spark.HierarchicalAlignmentClientTest
[INFO] Running org.janelia.render.client.spark.SIFTPointMatchClientTest

Usage: java -cp <render-module>-standalone.jar 
      org.janelia.render.client.spark.SIFTPointMatchClient [options]
  Options:
  * --pairJson
      JSON file where tile pairs are stored (.json, .gz, or .zip)
    --SIFTfdSize
      SIFT feature descriptor size: how many samples per row and column
      Default: 8
    --SIFTmaxScale
      SIFT maximum scale: minSize * minScale < size < maxSize * maxScale
      Default: 0.85
    --SIFTminScale
      SIFT minimum scale: minSize * minScale < size < maxSize * maxScale
      Default: 0.5
    --SIFTsteps
      SIFT steps per scale octave
      Default: 3
  * --baseDataUrl
      Base web service URL for data (e.g. http://host[:port]/render-ws/v1)
    --clipHeight
      Number of full scale pixels to include in rendered clips of TOP/BOTTOM 
      oriented montage tiles
    --clipWidth
      Number of full scale pixels to include in rendered clips of LEFT/RIGHT 
      oriented montage tiles
  * --collection
      Match collection name
    --expectedParallelism
      Fail immediately if Spark Context parallelism does not match this value
    --fillWithNoise
      Fill each canvas image with noise before rendering to improve point 
      match derivation
      Default: true
    --help
      Display this note
    --matchFilter
      Identifies if and how matches should be filtered
      Default: SINGLE_SET
      Possible Values: [NONE, SINGLE_SET, CONSENSUS_SETS, AGGREGATED_CONSENSUS_SETS]
    --matchInterpolatedModelLambda
      Lambda for interpolated match filtering (omit for standard filtering)
    --matchIterations
      Match filter iterations
      Default: 1000
    --matchMaxEpsilon
      Minimal allowed transfer error for match filtering
      Default: 20.0
    --matchMaxNumInliers
      Maximum number of inliers for match filtering
    --matchMaxTrust
      Reject match candidates with a cost larger than maxTrust * median cost
      Default: 3.0
    --matchMinInlierRatio
      Minimal ratio of inliers to candidates for match filtering
      Default: 0.0
    --matchMinNumInliers
      Minimal absolute number of inliers for match filtering
      Default: 4
    --matchModelType
      Type of model for match filtering
      Default: AFFINE
      Possible Values: [TRANSLATION, RIGID, SIMILARITY, AFFINE]
    --matchRegularizerModelType
      Type of regularizer model for interpolated match filtering (omit for 
      standard filtering)
      Possible Values: [TRANSLATION, RIGID, SIMILARITY, AFFINE]
    --matchRod
      Ratio of distances for matches
      Default: 0.92
    --maxFeatureCacheGb
      Maximum number of gigabytes of features to cache
      Default: 2
  * --owner
      Match collection owner
    --renderFilterListName
      Apply this filter list to all rendering (overrides renderWithFilter 
      option) 
    --renderFullScaleHeight
      Full scale height for all rendered tiles
    --renderFullScaleWidth
      Full scale width for all rendered tiles
    --renderScale
      Render tiles at this scale
      Default: 1.0
    --renderWithFilter
      Render tiles using default ad-hoc filter for intensity correction
      Default: true
    --renderWithoutMask
      Render tiles without a mask
      Default: true
    --requireStoredFeatures
      indicates that an exception should be thrown when stored features cannot 
      be found (if omitted, missing features are extracted from dynamically 
      rendered canvases)
      Default: false
    --rootFeatureDirectory
      Root directory for saved feature lists (omit if features should be 
      extracted from dynamically rendered canvases)

[INFO] Tests run: 1, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 0.025 s - in org.janelia.render.client.spark.SIFTPointMatchClientTest
[INFO] Running org.janelia.render.client.spark.BoxClientTest

Usage: java -cp <render-module>-standalone.jar 
      org.janelia.render.client.spark.BoxClient [options]
  Options:
  * --baseDataUrl
      Base web service URL for data (e.g. http://host[:port]/render-ws/v1)
    --binaryMask
      use binary mask (e.g. for DMG data)
      Default: false
    --createIGrid
      create an IGrid file
      Default: false
    --doFilter
      Use ad hoc filter to support alignment
      Default: false
    --filterListName
      Apply this filter list to all rendering (overrides doFilter option)
    --forceGeneration
      Regenerate boxes even if they already exist
      Default: false
    --format
      Format for rendered boxes
      Default: png
  * --height
      Height of each box
    --help
      Display this note
    --label
      Generate single color tile labels instead of actual tile images
      Default: false
    --maxLevel
      Maximum mipmap level to generate
      Default: 0
    --maxOverviewWidthAndHeight
      Max width and height of layer overview image (omit or set to zero to 
      disable overview generation)
    --maxZ
      Maximum Z value for layers to be processed
    --minZ
      Minimum Z value for layers to be processed
    --numberOfRenderGroups
      Total number of parallel jobs being used to render this layer (omit if 
      only one job is being used)
  * --owner
      Stack owner
  * --project
      Stack project
    --renderGroup
      Index (1-n) that identifies portion of layer to render (omit if only one 
      job is being used)
  * --rootDirectory
      Root directory for rendered tiles (e.g. 
      /tier2/flyTEM/nobackup/rendered_boxes) 
    --skipInterpolation
      skip interpolation (e.g. for DMG data)
      Default: false
    --sortByClusterGroupId
      Sort tile specs by cluster groupId so that larger clusters are rendered 
      on top of smaller clusters
      Default: false
  * --stack
      Stack name
  * --width
      Width of each box
    --z
      Explicit z values for sections to be rendered

[INFO] Tests run: 1, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 0.008 s - in org.janelia.render.client.spark.BoxClientTest
[INFO] Running org.janelia.render.client.spark.DMeshPointMatchClientTest

Usage: java -cp <render-module>-standalone.jar 
      org.janelia.render.client.spark.DMeshPointMatchClient [options]
  Options:
  * --pairJson
      JSON file where tile pairs are stored (.json, .gz, or .zip)
  * --baseDataUrl
      Base web service URL for data (e.g. http://host[:port]/render-ws/v1)
  * --collection
      Match collection name
    --dMeshLogToolOutput
      Log DMesh tool output even when processing is successful
      Default: false
    --dMeshParameters
      File containing DMesh parameters
      Default: /groups/flyTEM/flyTEM/match/dmesh/matchparams.txt
    --dMeshScript
      Script for launching DMesh
      Default: /groups/flyTEM/flyTEM/match/dmesh/run_ptest.sh
    --fillWithNoise
      Fill each canvas image with noise before rendering to improve point 
      match derivation
      Default: true
    --format
      Format for rendered canvases ('jpg', 'png', 'tif')
      Default: png
    --help
      Display this note
    --imageCacheParentDirectory
      Parent directory for cached (rendered) canvases
      Default: /dev/shm
    --maxImageCacheGb
      Maximum number of gigabytes of DMesh images to cache
      Default: 20
  * --owner
      Match collection owner
    --renderFilterListName
      Apply this filter list to all rendering (overrides renderWithFilter 
      option) 
    --renderFullScaleHeight
      Full scale height for all rendered tiles
    --renderFullScaleWidth
      Full scale width for all rendered tiles
    --renderScale
      Render tiles at this scale
      Default: 1.0
    --renderWithFilter
      Render tiles using default ad-hoc filter for intensity correction
      Default: true
    --renderWithoutMask
      Render tiles without a mask
      Default: true

[INFO] Tests run: 1, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 0.007 s - in org.janelia.render.client.spark.DMeshPointMatchClientTest

...

```

**Comment by martinschorb** [comment]
Confirm that it works for me now with both spark 2.4.7 and 3.0.0.

**Comment by trautmane** [comment]
To answer your question about the help output: yes, it is intentional.  That output comes from the automated unit tests that are run as part of the maven build process.  Automated testing of the command line clients is actually much more limited than I would like - but I at least try to invoke the parameter help code for each client.  Here is the code for the first test you noticed above: https://github.com/saalfeldlab/render/blob/master/render-ws-java-client/src/test/java/org/janelia/render/client/BoxRemovalClientTest.java
