### ISSUE TITLE
SIFT point match logger hardcoding driver api port

### ISSUE THREAD

**Issue by fcollman** [saalfeldlab/render#15]
the logging utilities with the SIFT point match client
LogUtilities.getExecutorsApiJson

currently has the 4040 port hardcoded in, and when submitting multiple applications the driver can dynamically assign ports, causing the job to fail if it isn't the only thing submitted to that node when the job starts.  Need to figure out a way to get around this... example error from the driver log below.

17/01/13 17:53:33 WARN Utils: Service 'SparkUI' could not bind on port 4040. Attempting port 4041.
17/01/13 17:53:33 INFO Utils: Successfully started service 'SparkUI' on port 4041.
17/01/13 17:53:33 INFO SparkUI: Bound SparkUI to 0.0.0.0, and started at http://10.128.24.33:4041
17/01/13 17:53:33 INFO SparkContext: Added JAR file:/pipeline/render/render-ws-spark-client/target/render-ws-spark-client-0.3.0-SNAPSHOT-standalone.jar at spark://10.128.24.33:45705/jars/render-ws-spark-client-0.3.0-SNAPSHOT-standalone.jar with timestamp 1484358813125
17/01/13 17:53:33 INFO StandaloneAppClient$ClientEndpoint: Connecting to master spark://atbigdawg.corp.alleninstitute.org:7077...
17/01/13 17:53:33 INFO TransportClientFactory: Successfully created connection to atbigdawg.corp.alleninstitute.org/10.128.24.91:7077 after 1 ms (0 ms spent in bootstraps)
17/01/13 17:53:33 INFO StandaloneSchedulerBackend: Connected to Spark cluster with app ID app-20170113175333-0022
17/01/13 17:53:33 INFO Utils: Successfully started service 'org.apache.spark.network.netty.NettyBlockTransferService' on port 36201.
17/01/13 17:53:33 INFO NettyBlockTransferService: Server created on 10.128.24.33:36201
17/01/13 17:53:33 INFO BlockManagerMaster: Registering BlockManager BlockManagerId(driver, 10.128.24.33, 36201)
17/01/13 17:53:33 INFO BlockManagerMasterEndpoint: Registering block manager 10.128.24.33:36201 with 5.2 GB RAM, BlockManagerId(driver, 10.128.24.33, 36201)
17/01/13 17:53:33 INFO BlockManagerMaster: Registered BlockManager BlockManagerId(driver, 10.128.24.33, 36201)
17/01/13 17:53:33 INFO StandaloneSchedulerBackend: SchedulerBackend is ready for scheduling beginning after reached minRegisteredResourcesRatio: 0.0
17/01/13 17:53:33 ERROR ClientRunner: run: caught exception
java.io.FileNotFoundException: http://localhost:4040/api/v1/applications/app-20170113175333-0022/executors
	at sun.net.www.protocol.http.HttpURLConnection.getInputStream0(HttpURLConnection.java:1872)
	at sun.net.www.protocol.http.HttpURLConnection.getInputStream(HttpURLConnection.java:1474)
	at java.net.URL.openStream(URL.java:1045)
	at org.janelia.render.client.spark.LogUtilities.getExecutorsApiJson(LogUtilities.java:61)
	at org.janelia.render.client.spark.SIFTPointMatchClient.run(SIFTPointMatchClient.java:155)
	at org.janelia.render.client.spark.SIFTPointMatchClient$1.runClient(SIFTPointMatchClient.java:135)
	at org.janelia.render.client.ClientRunner.run(ClientRunner.java:38)
	at org.janelia.render.client.spark.SIFTPointMatchClient.main(SIFTPointMatchClient.java:139)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.apache.spark.deploy.worker.DriverWrapper$.main(DriverWrapper.scala:58)
	at org.apache.spark.deploy.worker.DriverWrapper.main(DriverWrapper.scala)

**Comment by fcollman** [comment]
I think we want to use this..

https://spark.apache.org/docs/2.0.0/api/java/org/apache/spark/SparkContext.html#uiWebUrl()



On Tue, Jan 17, 2017 at 10:36 AM, Eric T. Trautman <notifications@github.com

**Comment by fcollman** [comment]
I updated my recent pull request with an update that makes use of this call
and it appears to work... build passed all tests, and below is a driver log
indicating that it connected fine to a 4041 port... this let me submit
multiple spark jobs to the cluster and not worry about later ones failing
due to the driver ports getting moved over.

If you dont' want to upgrade to spark 2.0, a more temporary hack would be
to simply try ports and look for your application on each one. conceptually
what they were suggesting here

http://stackoverflow.com/questions/37923380/determine-spark-ui-port-from-within-jupyter-pyspark

best,
forrest

17/01/18 10:29:42 WARN Utils: Service 'SparkUI' could not bind on port
4040. Attempting port 4041.
17/01/18 10:29:42 INFO Utils: Successfully started service 'SparkUI' on
port 4041.
17/01/18 10:29:42 INFO SparkUI: Bound SparkUI to 0.0.0.0, and started at
http://10.128.24.33:4041
17/01/18 10:29:42 INFO SparkContext: Added JAR
file:/pipeline/forrestrender/render-ws-spark-client/target/render-ws-spark-client-0.3.0-SNAPSHOT-standalone.jar
at spark://
10.128.24.33:39182/jars/render-ws-spark-client-0.3.0-SNAPSHOT-standalone.jar
with timestamp 1484764182202
17/01/18 10:29:42 INFO StandaloneAppClient$ClientEndpoint: Connecting to
master spark://atbigdawg.corp.alleninstitute.org:7077...
17/01/18 10:29:42 INFO TransportClientFactory: Successfully created
connection to atbigdawg.corp.alleninstitute.org/10.128.24.91:7077 after 1
ms (0 ms spent in bootstraps)
17/01/18 10:29:42 INFO StandaloneSchedulerBackend: Connected to Spark
cluster with app ID app-20170118102942-0048
17/01/18 10:29:42 INFO Utils: Successfully started service
'org.apache.spark.network.netty.NettyBlockTransferService' on port 37992.
17/01/18 10:29:42 INFO NettyBlockTransferService: Server created on
10.128.24.33:37992
17/01/18 10:29:42 INFO BlockManagerMaster: Registering BlockManager
BlockManagerId(driver, 10.128.24.33, 37992)
17/01/18 10:29:42 INFO BlockManagerMasterEndpoint: Registering block
manager 10.128.24.33:37992 with 10.0 GB RAM, BlockManagerId(driver,
10.128.24.33, 37992)
17/01/18 10:29:42 INFO BlockManagerMaster: Registered BlockManager
BlockManagerId(driver, 10.128.24.33, 37992)
17/01/18 10:29:42 INFO StandaloneSchedulerBackend: SchedulerBackend is
ready for scheduling beginning after reached minRegisteredResourcesRatio:
0.0
17/01/18 10:29:43 INFO SIFTPointMatchClient: run: appId is
app-20170118102942-0048, executors data is [ {
  "id" : "driver",
  "hostPort" : "10.128.24.33:37992",
  "isActive" : true,
  "rddBlocks" : 0,
  "memoryUsed" : 0,
  "diskUsed" : 0,
  "totalCores" : 0,
  "maxTasks" : 0,
  "activeTasks" : 0,
  "failedTasks" : 0,
  "completedTasks" : 0,
  "totalTasks" : 0,
  "totalDuration" : 0,
  "totalGCTime" : 0,
  "totalInputBytes" : 0,
  "totalShuffleRead" : 0,
  "totalShuffleWrite" : 0,
  "maxMemory" : 10692014899,
  "executorLogs" : { }
} ]
17/01/18 10:29:43 INFO SIFTPointMatchClient: generateMatchesForPairFile:
pairJsonFileName is
/nas3/data/M270907_Scnn1aTg2Tdt_13/processed/tilepairs_dz10_1235_1260.json
17/01/18 10:29:43 INFO RenderableCanvasIdPairsUtilities: load: entry,
path=/nas3/data/M270907_Scnn1aTg2Tdt_13/processed/tilepairs_dz10_1235_1260.json
17/01/18 10:29:44 INFO RenderableCanvasIdPairsUtilities: load: exit, loaded
69836 pairs
17/01/18 10:29:44 INFO RenderableCanvasIdPairsUtilities:
getRenderParametersUrlTemplateForRun: returning
http://ibs-forrestc-ux1:8080/render-ws/v1/owner/Sharmishtaas/project/M270907_Scnn1aTg2Tdt_13/stack/ALIGNEDSTACK_JAN3_DAPI_1_NORM/tile/{id}/render-parameters?scale=0.5&excludeMask=true&normali
zeForMatching=true
17/01/18 10:29:44 INFO MemoryStore: Block broadcast_0 stored as values in
memory (estimated size 48.0 B, free 10.0 GB)
17/01/18 10:29:44 INFO MemoryStore: Block broadcast_0_piece0 stored as
bytes in memory (estimated size 120.0 B, free 10.0 GB)
17/01/18 10:29:44 INFO BlockManagerInfo: Added broadcast_0_piece0 in memory
on 10.128.24.33:37992 (size: 120.0 B, free: 10.0 GB)
17/01/18 10:29:44 INFO SparkContext: Created broadcast 0 from broadcast at
SIFTPointMatchClient.java:196
17/01/18 10:29:44 INFO MemoryStore: Block broadcast_1 stored as values in
memory (estimated size 600.0 B, free 10.0 GB)
17/01/18 10:29:44 INFO MemoryStore: Block broadcast_1_piece0 stored as
bytes in memory (estimated size 790.0 B, free 10.0 GB)
17/01/18 10:29:44 INFO BlockManagerInfo: Added broadcast_1_piece0 in memory
on 10.128.24.33:37992 (size: 790.0 B, free: 10.0 GB)
17/01/18 10:29:44 INFO SparkContext: Created broadcast 1 from broadcast at
SIFTPointMatchClient.java:197
17/01/18 10:29:44 INFO MemoryStore: Block broadcast_2 stored as values in
memory (estimated size 176.0 B, free 10.0 GB)
17/01/18 10:29:44 INFO MemoryStore: Block broadcast_2_piece0 stored as
bytes in memory (estimated size 335.0 B, free 10.0 GB)
17/01/18 10:29:44 INFO BlockManagerInfo: Added broadcast_2_piece0 in memory
on 10.128.24.33:37992 (size: 335.0 B, free: 10.0 GB)
17/01/18 10:29:44 INFO SparkContext: Created broadcast 2 from broadcast at
SIFTPointMatchClient.java:199
17/01/18 10:29:44 INFO SIFTPointMatchClient: run: 5000 partitions, debug
string is:
(5000) MapPartitionsRDD[2] at mapPartitionsWithIndex at
SIFTPointMatchClient.java:264 []
  |    MapPartitionsRDD[1] at mapPartitionsWithIndex at
SIFTPointMatchClient.java:204 []
