### ISSUE TITLE
Render Web Services Example leads to HTTP status 500 Error

### ISSUE THREAD

**Issue by lanery** [saalfeldlab/render#71]
I've just started out with render and was trying to work through the [Render Web Services Example](https://github.com/saalfeldlab/render/blob/master/docs/src/site/markdown/render-ws-example.md#render-web-services-example), and ran into a 500 error when trying to run
```
# complete v1_acquire stack
${CLIENT_SCRIPTS}/manage_stacks.sh ${EXAMPLE_1_PARAMS} --stack v1_acquire --action SET_STATE --stackState COMPLETE
```
under the [Import Acquisition Data](https://github.com/saalfeldlab/render/blob/master/docs/src/site/markdown/render-ws-example.md#2-import-acquisition-data-acquire) step. All subsequent third commands (those ending with `--stackState COMPLETE`) also fail with the same 500 error, while the others all completed successfully.

If it helps, I'm running an Ubuntu 16.04 LTS virtual machine (named 'janelia', which is why 'janelia' shows up all over the traceback), and followed the basic installation instructions exactly besides using the newest version of MongoDB.

I would appreciate any feedback, thank you!

Full traceback:
```
rlane@janelia:~/development/render$ ${CLIENT_SCRIPTS}/manage_stacks.sh ${EXAMPLE_1_PARAMS} --stack v1_acquire --action SET_STATE --stackState COMPLETE

  Running: /home/rlane/development/render/deploy/jdk1.8.0_131/bin/java -cp /home/rlane/development/render/render-ws-java-client/target/render-ws-java-client-2.0.1-SNAPSHOT-standalone.jar -Xms1G -Xmx1G -Djava.awt.headless=true -XX:+UseSerialGC org.janelia.render.client.StackClient --baseDataUrl http://localhost:8080/render-ws/v1 --owner demo --project example_1 --stack v1_acquire --action SET_STATE --stackState COMPLETE


17:12:43.529 [main] INFO  [org.janelia.render.client.ClientRunner] run: entry
17:12:43.681 [main] INFO  [org.janelia.render.client.StackClient] runClient: entry, parameters={
  "renderWeb" : {
    "baseDataUrl" : "http://localhost:8080/render-ws/v1",
    "owner" : "demo",
    "project" : "example_1"
  },
  "stack" : "v1_acquire",
  "action" : "SET_STATE",
  "stackState" : "COMPLETE"
}
17:12:43.936 [main] INFO  [org.janelia.render.client.RenderDataClient] getStackMetaData: submitting GET http://localhost:8080/render-ws/v1/owner/demo/project/example_1/stack/v1_acquire
17:12:44.009 [main] INFO  [org.janelia.render.client.StackClient] setStackState: before update, stackMetaData={
  "stackId" : {
    "owner" : "demo",
    "project" : "example_1",
    "stack" : "v1_acquire"
  },
  "state" : "LOADING",
  "lastModifiedTimestamp" : "2017-12-12T15:43:25.329Z",
  "currentVersionNumber" : 3,
  "currentVersion" : {
    "createTimestamp" : "2017-12-12T15:43:25.300Z",
    "cycleNumber" : 1,
    "cycleStepNumber" : 1
  }
}
17:12:44.023 [main] INFO  [org.janelia.render.client.RenderDataClient] setStackState: submitting PUT http://localhost:8080/render-ws/v1/owner/demo/project/example_1/stack/v1_acquire/state/COMPLETE
17:12:44.036 [main] ERROR [org.janelia.render.client.ClientRunner] run: caught exception
org.apache.http.client.ClientProtocolException: HTTP status 500 with body

  null

returned for

  PUT http://localhost:8080/render-ws/v1/owner/demo/project/example_1/stack/v1_acquire/state/COMPLETE

	at org.janelia.render.client.response.BaseResponseHandler.getValidatedResponseEntity(BaseResponseHandler.java:93) ~[render-ws-java-client-2.0.1-SNAPSHOT-standalone.jar:na]
	at org.janelia.render.client.response.ResourceCreatedResponseHandler.handleResponse(ResourceCreatedResponseHandler.java:30) ~[render-ws-java-client-2.0.1-SNAPSHOT-standalone.jar:na]
	at org.janelia.render.client.response.ResourceCreatedResponseHandler.handleResponse(ResourceCreatedResponseHandler.java:15) ~[render-ws-java-client-2.0.1-SNAPSHOT-standalone.jar:na]
	at org.apache.http.impl.client.CloseableHttpClient.execute(CloseableHttpClient.java:218) ~[render-ws-java-client-2.0.1-SNAPSHOT-standalone.jar:na]
	at org.apache.http.impl.client.CloseableHttpClient.execute(CloseableHttpClient.java:160) ~[render-ws-java-client-2.0.1-SNAPSHOT-standalone.jar:na]
	at org.apache.http.impl.client.CloseableHttpClient.execute(CloseableHttpClient.java:136) ~[render-ws-java-client-2.0.1-SNAPSHOT-standalone.jar:na]
	at org.janelia.render.client.RenderDataClient.setStackState(RenderDataClient.java:545) ~[render-ws-java-client-2.0.1-SNAPSHOT-standalone.jar:na]
	at org.janelia.render.client.StackClient.setStackState(StackClient.java:279) [render-ws-java-client-2.0.1-SNAPSHOT-standalone.jar:na]
	at org.janelia.render.client.StackClient$1.runClient(StackClient.java:169) ~[render-ws-java-client-2.0.1-SNAPSHOT-standalone.jar:na]
	at org.janelia.render.client.ClientRunner.run(ClientRunner.java:38) ~[render-ws-java-client-2.0.1-SNAPSHOT-standalone.jar:na]
	at org.janelia.render.client.StackClient.main(StackClient.java:177) [render-ws-java-client-2.0.1-SNAPSHOT-standalone.jar:na]
17:12:44.036 [main] INFO  [org.janelia.render.client.ClientRunner] run: exit, processing failed after 0 hours, 0 minutes, 0 seconds
rlane@janelia:~/development/render$ 
```

**Comment by trautmane** [comment]
Hi Ryan,

Can you take a look at the <date>-jetty.log file in deploy/jetty_base/logs/2017-12 
and post the exception stack trace from the log?
I'm hoping that will give me a better idea of what has gone wrong.

Thanks,
Eric

**Comment by lanery** [comment]
Hi Eric,

Thank you for looking into my issue, I really appreciate it. I believe I've put the relevant stack trace below, but just in case, I've attached the entire logfile for a new session that I've just run today in which I ran
```
${CLIENT_SCRIPTS}/manage_stacks.sh ${EXAMPLE_1_PARAMS} --stack v1_acquire --action CREATE --cycleNumber 1 --cycleStepNumber 1 
${CLIENT_SCRIPTS}/import_json.sh ${EXAMPLE_1_PARAMS} --stack v1_acquire --transformFile ${EXAMPLE_1_DIR}/cycle1_step1_acquire_transforms.json ${EXAMPLE_1_DIR}/cycle1_step1_acquire_tiles.json 
${CLIENT_SCRIPTS}/manage_stacks.sh ${EXAMPLE_1_PARAMS} --stack v1_acquire --action SET_STATE --stackState COMPLETE
```
In any event, all I can make out is that it looks like a MongoDB issue "The 'cursor' option is required, except for aggregate with the explain argument"

Thanks,
Ryan

[2017-12-13-jetty.log](https://github.com/saalfeldlab/render/files/1554706/2017-12-13-jetty.log)
```
2017-12-13 09:16:56,862 [qtp1006485584-16] ERROR [org.janelia.render.service.util.RenderServiceUtil] service failure
com.mongodb.MongoCommandException: Command failed with error 9: 'The 'cursor' option is required, except for aggregate with the explain argument' on server localhost:27017. The full response is { "ok" : 0.0, "errmsg" : "The 'cursor' option is required, except for aggregate with the explain argument", "code" : 9, "codeName" : "FailedToParse" }
	at com.mongodb.connection.ProtocolHelper.getCommandFailureException(ProtocolHelper.java:86)
	at com.mongodb.connection.CommandProtocol.execute(CommandProtocol.java:119)
	at com.mongodb.connection.DefaultServer$DefaultServerProtocolExecutor.execute(DefaultServer.java:159)
	at com.mongodb.connection.DefaultServerConnection.executeProtocol(DefaultServerConnection.java:286)
	at com.mongodb.connection.DefaultServerConnection.command(DefaultServerConnection.java:173)
	at com.mongodb.operation.CommandOperationHelper.executeWrappedCommandProtocol(CommandOperationHelper.java:215)
	at com.mongodb.operation.CommandOperationHelper.executeWrappedCommandProtocol(CommandOperationHelper.java:206)
	at com.mongodb.operation.CommandOperationHelper.executeWrappedCommandProtocol(CommandOperationHelper.java:145)
	at com.mongodb.operation.CommandOperationHelper.executeWrappedCommandProtocol(CommandOperationHelper.java:138)
	at com.mongodb.operation.AggregateToCollectionOperation$1.call(AggregateToCollectionOperation.java:165)
	at com.mongodb.operation.AggregateToCollectionOperation$1.call(AggregateToCollectionOperation.java:162)
	at com.mongodb.operation.OperationHelper.withConnectionSource(OperationHelper.java:230)
	at com.mongodb.operation.OperationHelper.withConnection(OperationHelper.java:221)
	at com.mongodb.operation.AggregateToCollectionOperation.execute(AggregateToCollectionOperation.java:162)
	at com.mongodb.operation.AggregateToCollectionOperation.execute(AggregateToCollectionOperation.java:52)
	at com.mongodb.Mongo.execute(Mongo.java:782)
	at com.mongodb.Mongo$2.execute(Mongo.java:765)
	at com.mongodb.AggregateIterableImpl.execute(AggregateIterableImpl.java:135)
	at com.mongodb.AggregateIterableImpl.first(AggregateIterableImpl.java:107)
	at org.janelia.render.service.dao.RenderDao.deriveSectionData(RenderDao.java:1209)
	at org.janelia.render.service.dao.RenderDao.ensureIndexesAndDeriveStats(RenderDao.java:1018)
	at org.janelia.render.service.StackMetaDataService.setStackState(StackMetaDataService.java:883)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.jboss.resteasy.core.MethodInjectorImpl.invoke(MethodInjectorImpl.java:140)
	at org.jboss.resteasy.core.ResourceMethodInvoker.invokeOnTarget(ResourceMethodInvoker.java:294)
	at org.jboss.resteasy.core.ResourceMethodInvoker.invoke(ResourceMethodInvoker.java:248)
	at org.jboss.resteasy.core.ResourceMethodInvoker.invoke(ResourceMethodInvoker.java:235)
	at org.jboss.resteasy.core.SynchronousDispatcher.invoke(SynchronousDispatcher.java:402)
	at org.jboss.resteasy.core.SynchronousDispatcher.invoke(SynchronousDispatcher.java:209)
	at org.jboss.resteasy.plugins.server.servlet.ServletContainerDispatcher.service(ServletContainerDispatcher.java:227)
	at org.jboss.resteasy.plugins.server.servlet.HttpServletDispatcher.service(HttpServletDispatcher.java:56)
	at org.jboss.resteasy.plugins.server.servlet.HttpServletDispatcher.service(HttpServletDispatcher.java:51)
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:790)
	at org.eclipse.jetty.servlet.ServletHolder.handle(ServletHolder.java:835)
	at org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1685)
	at org.eclipse.jetty.servlets.CrossOriginFilter.handle(CrossOriginFilter.java:308)
	at org.eclipse.jetty.servlets.CrossOriginFilter.doFilter(CrossOriginFilter.java:262)
	at org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1668)
	at org.eclipse.jetty.servlet.ServletHandler.doHandle(ServletHandler.java:581)
	at org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:143)
	at org.eclipse.jetty.security.SecurityHandler.handle(SecurityHandler.java:548)
	at org.eclipse.jetty.server.session.SessionHandler.doHandle(SessionHandler.java:226)
	at org.eclipse.jetty.server.handler.ContextHandler.doHandle(ContextHandler.java:1158)
	at org.eclipse.jetty.servlet.ServletHandler.doScope(ServletHandler.java:511)
	at org.eclipse.jetty.server.session.SessionHandler.doScope(SessionHandler.java:185)
	at org.eclipse.jetty.server.handler.ContextHandler.doScope(ContextHandler.java:1090)
	at org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:141)
	at org.eclipse.jetty.server.handler.ContextHandlerCollection.handle(ContextHandlerCollection.java:213)
	at org.eclipse.jetty.server.handler.HandlerCollection.handle(HandlerCollection.java:109)
	at org.eclipse.jetty.server.handler.HandlerWrapper.handle(HandlerWrapper.java:119)
	at org.eclipse.jetty.server.Server.handle(Server.java:517)
	at org.eclipse.jetty.server.HttpChannel.handle(HttpChannel.java:308)
	at org.eclipse.jetty.server.HttpConnection.onFillable(HttpConnection.java:242)
	at org.eclipse.jetty.io.AbstractConnection$ReadCallback.succeeded(AbstractConnection.java:273)
	at org.eclipse.jetty.io.FillInterest.fillable(FillInterest.java:95)
	at org.eclipse.jetty.io.SelectChannelEndPoint$2.run(SelectChannelEndPoint.java:75)
	at org.eclipse.jetty.util.thread.strategy.ExecuteProduceConsume.produceAndRun(ExecuteProduceConsume.java:213)
	at org.eclipse.jetty.util.thread.strategy.ExecuteProduceConsume.run(ExecuteProduceConsume.java:147)
	at org.eclipse.jetty.util.thread.QueuedThreadPool.runJob(QueuedThreadPool.java:654)
	at org.eclipse.jetty.util.thread.QueuedThreadPool$3.run(QueuedThreadPool.java:572)
	at java.lang.Thread.run(Thread.java:748)
```

**Comment by lanery** [comment]
Hi again Eric,

After looking around online, it looked like it was an issue related to aggregate in MongoDB 3.5+. After downgrading to MongoDB 3.4, setting the state to COMPLETE works throughout. Thanks for pointing me in the direction of the log files.

Now the only hangup is that I think `--montageStack` ought to be `--stack` in step 5 for
```
${CLIENT_SCRIPTS}/generate_warp_transforms.sh ${EXAMPLE_1_PARAMS} --alignStack v1_align --montageStack v1_montage --targetStack v1_align_tps 3407 3408  
```
By making this change, everything seems to work now, thank you!
